// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/resources/proto/proto.proto

package cn.acexy.tech.grpc.demo.simple.client.proto;

/**
 * <pre>
 * 定义一个GRPC服务
 * </pre>
 *
 * Protobuf service {@code proto.MessageCall}
 */
public  abstract class MessageCall
    implements com.google.protobuf.Service {
  protected MessageCall() {}

  public interface Interface {
    /**
     * <pre>
     *  内含call接口 需要一个RequestContext参数并返回ResponseContext类型的参数
     * </pre>
     *
     * <code>rpc sendMsg(.proto.RequestContext) returns (.proto.ResponseContext);</code>
     */
    public abstract void sendMsg(
        com.google.protobuf.RpcController controller,
        cn.acexy.tech.grpc.demo.simple.client.proto.RequestContext request,
        com.google.protobuf.RpcCallback<cn.acexy.tech.grpc.demo.simple.client.proto.ResponseContext> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new MessageCall() {
      @java.lang.Override
      public  void sendMsg(
          com.google.protobuf.RpcController controller,
          cn.acexy.tech.grpc.demo.simple.client.proto.RequestContext request,
          com.google.protobuf.RpcCallback<cn.acexy.tech.grpc.demo.simple.client.proto.ResponseContext> done) {
        impl.sendMsg(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.sendMsg(controller, (cn.acexy.tech.grpc.demo.simple.client.proto.RequestContext)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return cn.acexy.tech.grpc.demo.simple.client.proto.RequestContext.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return cn.acexy.tech.grpc.demo.simple.client.proto.ResponseContext.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <pre>
   *  内含call接口 需要一个RequestContext参数并返回ResponseContext类型的参数
   * </pre>
   *
   * <code>rpc sendMsg(.proto.RequestContext) returns (.proto.ResponseContext);</code>
   */
  public abstract void sendMsg(
      com.google.protobuf.RpcController controller,
      cn.acexy.tech.grpc.demo.simple.client.proto.RequestContext request,
      com.google.protobuf.RpcCallback<cn.acexy.tech.grpc.demo.simple.client.proto.ResponseContext> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return cn.acexy.tech.grpc.demo.simple.client.proto.ProtoGrpcClass.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.sendMsg(controller, (cn.acexy.tech.grpc.demo.simple.client.proto.RequestContext)request,
          com.google.protobuf.RpcUtil.<cn.acexy.tech.grpc.demo.simple.client.proto.ResponseContext>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return cn.acexy.tech.grpc.demo.simple.client.proto.RequestContext.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return cn.acexy.tech.grpc.demo.simple.client.proto.ResponseContext.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends cn.acexy.tech.grpc.demo.simple.client.proto.MessageCall implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void sendMsg(
        com.google.protobuf.RpcController controller,
        cn.acexy.tech.grpc.demo.simple.client.proto.RequestContext request,
        com.google.protobuf.RpcCallback<cn.acexy.tech.grpc.demo.simple.client.proto.ResponseContext> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        cn.acexy.tech.grpc.demo.simple.client.proto.ResponseContext.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          cn.acexy.tech.grpc.demo.simple.client.proto.ResponseContext.class,
          cn.acexy.tech.grpc.demo.simple.client.proto.ResponseContext.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public cn.acexy.tech.grpc.demo.simple.client.proto.ResponseContext sendMsg(
        com.google.protobuf.RpcController controller,
        cn.acexy.tech.grpc.demo.simple.client.proto.RequestContext request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public cn.acexy.tech.grpc.demo.simple.client.proto.ResponseContext sendMsg(
        com.google.protobuf.RpcController controller,
        cn.acexy.tech.grpc.demo.simple.client.proto.RequestContext request)
        throws com.google.protobuf.ServiceException {
      return (cn.acexy.tech.grpc.demo.simple.client.proto.ResponseContext) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        cn.acexy.tech.grpc.demo.simple.client.proto.ResponseContext.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:proto.MessageCall)
}

