// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/resources/proto/proto.proto

package cn.acexy.tech.grpc.demo.simple.client.proto;

public final class ProtoGrpcClass {
  private ProtoGrpcClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_RequestContext_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_RequestContext_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ResponseContext_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ResponseContext_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n main/resources/proto/proto.proto\022\005prot" +
      "o\"/\n\016RequestContext\022\017\n\007context\030\001 \001(\t\022\014\n\004" +
      "flag\030\002 \001(\010\"/\n\017ResponseContext\022\017\n\007context" +
      "\030\001 \001(\t\022\013\n\003len\030\002 \001(\0052I\n\013MessageCall\022:\n\007se" +
      "ndMsg\022\025.proto.RequestContext\032\026.proto.Res" +
      "ponseContext\"\000BX\n+cn.acexy.tech.grpc.dem" +
      "o.simple.client.protoB\016ProtoGrpcClassP\001Z" +
      "\024rpc/grpc/proto;proto\210\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_RequestContext_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_RequestContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_RequestContext_descriptor,
        new java.lang.String[] { "Context", "Flag", });
    internal_static_proto_ResponseContext_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_ResponseContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ResponseContext_descriptor,
        new java.lang.String[] { "Context", "Len", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
