// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/resources/proto/proto.proto

package cn.acexy.tech.grpc.demo.simple.client.proto;

public interface RequestContextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.RequestContext)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string context = 1;</code>
   * @return The context.
   */
  java.lang.String getContext();
  /**
   * <code>string context = 1;</code>
   * @return The bytes for context.
   */
  com.google.protobuf.ByteString
      getContextBytes();

  /**
   * <code>bool flag = 2;</code>
   * @return The flag.
   */
  boolean getFlag();
}
