// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb/user/user.proto

package cn.acexy.tech.grpc.pb;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pbuser.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
