// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb/user/user.proto

package cn.acexy.tech.grpc.pb;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pbuser.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .pbuser.User users = 1;</code>
   */
  java.util.List<cn.acexy.tech.grpc.pb.User> 
      getUsersList();
  /**
   * <code>repeated .pbuser.User users = 1;</code>
   */
  cn.acexy.tech.grpc.pb.User getUsers(int index);
  /**
   * <code>repeated .pbuser.User users = 1;</code>
   */
  int getUsersCount();
  /**
   * <code>repeated .pbuser.User users = 1;</code>
   */
  java.util.List<? extends cn.acexy.tech.grpc.pb.UserOrBuilder> 
      getUsersOrBuilderList();
  /**
   * <code>repeated .pbuser.User users = 1;</code>
   */
  cn.acexy.tech.grpc.pb.UserOrBuilder getUsersOrBuilder(
      int index);
}
