// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb/user/user.proto

package cn.acexy.tech.grpc.pb;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pbuser.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.pbuser.Sex sex = 3;</code>
   * @return The enum numeric value on the wire for sex.
   */
  int getSexValue();
  /**
   * <code>.pbuser.Sex sex = 3;</code>
   * @return The sex.
   */
  cn.acexy.tech.grpc.pb.Sex getSex();

  /**
   * <code>uint32 age = 4;</code>
   * @return The age.
   */
  int getAge();
}
